### ISSUE TITLE
Can't compile the ppm module

### ISSUE THREAD

**Issue by chanurahemal** [ltb-project/ppm#10]
Hi,
I cloned ppm module and tried to compile with openldap 2.4.46 source. Initially it gave following error when i execute make CONFIG=.......... command.
````
****ppm.c:11:10: fatal error: 'portable.h' file not found
Then i renamed portable.hin file(with some other files as ell) to portable.h and that error was gone. But still i am getting following error.

In file included from ppm.c:12:
In file included from ../../../servers/slapd/slap.h:37:
../../../include/ac/regex.h:29:2: error: "No POSIX REGEX available."
#error "No POSIX REGEX available."
 ^
In file included from ppm.c:12:
In file included from ../../../servers/slapd/slap.h:55:
In file included from ../../../include/ldap_pvt.h:531:
In file included from ../../../include/ldap_pvt_uc.h:27:
../../../include/ac/bytes.h:31:3: error: "AC_INT4_TYPE?"
#       error "AC_INT4_TYPE?"
        ^ 
````

Please someone can help me to solve this problem as it is very very urgent.

Thank you

**Comment by davidcoutadeur** [comment]
Looking at this point

**Comment by davidcoutadeur** [comment]
@chanurahemal: which ppm version did you use? 1.6 release or last master?
If using last master, please consider the new Makefile option OLDAP_SOURCES variable to point to your openldap source installation directory.

By the way, ppm master compiles correctly against last 2.4.46 openldap

**Comment by chanurahemal** [comment]
Hi,
Thank you very much
I am using master version and 2.4.46 openldap.
i set openldap source directly to OLDAP_SOURCES path.

**Comment by davidcoutadeur** [comment]
@chanurahemal: and so it is working for you now ?

**Comment by chanurahemal** [comment]
Hi tried last Friday, but not working

**Comment by davidcoutadeur** [comment]
Can't reproduce the error...
Which operating system?
Did you use official OpenLDAP 2.4.46 release?

**Comment by chanurahemal** [comment]
Yes, official one.
I used Mac and SentOS both.
Just in case can you send me the link to download openldap source which you
used?

**Comment by chanurahemal** [comment]
This is the link I used to download openldap
https://www.openldap.org/software/download/

**Comment by davidcoutadeur** [comment]
The link is ok.
You should not rename files .hin.
portable.h is available in directory include/portable.h, once you have compiled OpenLDAP:
```
./configure
make
```
So you should just compile OpenLDAP first.

**Comment by chanurahemal** [comment]
Once I try that I get following error.

configure: WARNING: you should use --build, --host, --target
Configuring OpenLDAP 2.4.46-Release ...
checking build system type... Invalid configuration `make': machine `make'
not recognized
configure: error: /bin/sh build/config.sub make failed


Sorry I am not a C programmer, but Java :)

**Comment by davidcoutadeur** [comment]
As you are on a specific machine (MacOS), you may have to provide specific options as mentioned:
- build
- host
- target

I don't know very well these options. If you experience difficulties with them, I suggest you read this: http://www.openldap.org/doc/admin24/install.html, then contact OpenLDAP community on their mailing list: http://www.openldap.org/lists/

As it is not a problem in ppm library, I close this issue. You can reoppen if you face new problem after you succeed in compiling OpenLDAP.

**Comment by chanurahemal** [comment]
I built this one in CentoOS as well, but getting the same error

**Comment by davidcoutadeur** [comment]
What error did you get?
Error when compiling OpenLDAP or while compiling ppm?
Did you try compiling OpenLDAP first?

**Comment by coudot** [comment]
@chanurahemal note that I compiled it yesterday to build OpenLDAP RPM and it worked well. See https://github.com/ltb-project/openldap-rpm/blob/master/SPECS/openldap-ltb.spec
